import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect } from "react";
import type { NextPageWithLayout } from "./_app";

// external imports
import Button from "@/components/Button";
import DefaultLayout from "@/layouts/DefaultLayout";

const Home: NextPageWithLayout = () => {
  const router = useRouter();
  useEffect(() => {
    router.push("/app");
  }, [router]);

  return (
    <>
      <Head>
        <title>Amzn Store</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full flex-col items-center justify-center gap-7 px-4 sm:w-[95vw]">
        <h1 className="text-xl font-semibold md:text-3xl">
          Redirecting to the app page
        </h1>
        <Link href="/app">
          <Button aria-label="go to app page">Go to app</Button>
        </Link>
      </main>
    </>
  );
};

export default Home;

Home.getLayout = (page) => <DefaultLayout>{page}</DefaultLayout>;
